module.exports = {
  ETH_NODE_RPC_URL: {
    mainnet: 'https://mainnet.infura.io/v3/<your INFURA project ID>',
    kovan: 'https://kovan.infura.io/v3/<your INFURA project ID>'
  },
  MESSAGE_TO_SIGN: 'This is a message generated by enzypt.io, by signing this message you are proving that you own the address: %.\nRandom string: %'
}
