module.exports = {
  ETH_NODE_RPC_URL: {
    mainnet: 'https://mainnet.infura.io/T1YIsUqqHW568dijGClq',
    kovan: 'https://kovan.infura.io/T1YIsUqqHW568dijGClq'
    // kovan: 'http://localhost:8545'
  },
  MESSAGE_TO_SIGN: 'This is a message generated by enzypt.io, by signing this message you are proving that you own the address: %.\nRandom string: %'
}
