module.exports = {
  ETH_NODE_RPC_URL: {
    mainnet: 'https://mainnet.infura.io/v3/47a13f086c934a84913a753195b3e9cc',
    kovan: 'https://kovan.infura.io/v3/47a13f086c934a84913a753195b3e9cc'
  },
  MESSAGE_TO_SIGN: 'This is a message generated by enzypt.io, by signing this message you are proving that you own the address: %.\nRandom string: %'
}
